# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

    The version of the OpenAPI document: 2.0.0
    Contact: joel@spacetraders.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401

from typing import Any, List, Optional
from pydantic import BaseModel, Field, StrictStr, ValidationError, validator
from openapi_client.models.ship_condition_event import ShipConditionEvent
from typing import Union, Any, List, TYPE_CHECKING
from pydantic import StrictStr, Field

EXTRACTRESOURCES201RESPONSEDATAEVENTSINNER_ONE_OF_SCHEMAS = ["ShipConditionEvent"]

class ExtractResources201ResponseDataEventsInner(BaseModel):
    """
    ExtractResources201ResponseDataEventsInner
    """
    # data type: ShipConditionEvent
    oneof_schema_1_validator: Optional[ShipConditionEvent] = None
    if TYPE_CHECKING:
        actual_instance: Union[ShipConditionEvent]
    else:
        actual_instance: Any
    one_of_schemas: List[str] = Field(EXTRACTRESOURCES201RESPONSEDATAEVENTSINNER_ONE_OF_SCHEMAS, const=True)

    class Config:
        validate_assignment = True

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ExtractResources201ResponseDataEventsInner.construct()
        error_messages = []
        match = 0
        # validate data type: ShipConditionEvent
        if not isinstance(v, ShipConditionEvent):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ShipConditionEvent`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ExtractResources201ResponseDataEventsInner with oneOf schemas: ShipConditionEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ExtractResources201ResponseDataEventsInner with oneOf schemas: ShipConditionEvent. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: dict) -> ExtractResources201ResponseDataEventsInner:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> ExtractResources201ResponseDataEventsInner:
        """Returns the object represented by the json string"""
        instance = ExtractResources201ResponseDataEventsInner.construct()
        error_messages = []
        match = 0

        # deserialize data into ShipConditionEvent
        try:
            instance.actual_instance = ShipConditionEvent.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ExtractResources201ResponseDataEventsInner with oneOf schemas: ShipConditionEvent. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ExtractResources201ResponseDataEventsInner with oneOf schemas: ShipConditionEvent. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        to_json = getattr(self.actual_instance, "to_json", None)
        if callable(to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        to_dict = getattr(self.actual_instance, "to_dict", None)
        if callable(to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.dict())


