# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

    The version of the OpenAPI document: 2.0.0
    Contact: joel@spacetraders.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime

from pydantic import BaseModel, Field
from openapi_client.models.ship_nav_route_waypoint import ShipNavRouteWaypoint

class ShipNavRoute(BaseModel):
    """
    The routing information for the ship's most recent transit or current location.  # noqa: E501
    """
    destination: ShipNavRouteWaypoint = Field(...)
    origin: ShipNavRouteWaypoint = Field(...)
    departure_time: datetime = Field(default=..., alias="departureTime", description="The date time of the ship's departure.")
    arrival: datetime = Field(default=..., description="The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival.")
    __properties = ["destination", "origin", "departureTime", "arrival"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ShipNavRoute:
        """Create an instance of ShipNavRoute from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of destination
        if self.destination:
            _dict['destination'] = self.destination.to_dict()
        # override the default output from pydantic by calling `to_dict()` of origin
        if self.origin:
            _dict['origin'] = self.origin.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ShipNavRoute:
        """Create an instance of ShipNavRoute from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ShipNavRoute.parse_obj(obj)

        _obj = ShipNavRoute.parse_obj({
            "destination": ShipNavRouteWaypoint.from_dict(obj.get("destination")) if obj.get("destination") is not None else None,
            "origin": ShipNavRouteWaypoint.from_dict(obj.get("origin")) if obj.get("origin") is not None else None,
            "departure_time": obj.get("departureTime"),
            "arrival": obj.get("arrival")
        })
        return _obj


