# coding: utf-8

"""
    SpaceTraders API

    SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

    The version of the OpenAPI document: 2.0.0
    Contact: joel@spacetraders.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, constr
from openapi_client.models.ship_nav_flight_mode import ShipNavFlightMode
from openapi_client.models.ship_nav_route import ShipNavRoute
from openapi_client.models.ship_nav_status import ShipNavStatus

class ShipNav(BaseModel):
    """
    The navigation information of the ship.  # noqa: E501
    """
    system_symbol: constr(strict=True, min_length=1) = Field(default=..., alias="systemSymbol", description="The symbol of the system.")
    waypoint_symbol: constr(strict=True, min_length=1) = Field(default=..., alias="waypointSymbol", description="The symbol of the waypoint.")
    route: ShipNavRoute = Field(...)
    status: ShipNavStatus = Field(...)
    flight_mode: ShipNavFlightMode = Field(default=..., alias="flightMode")
    __properties = ["systemSymbol", "waypointSymbol", "route", "status", "flightMode"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ShipNav:
        """Create an instance of ShipNav from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of route
        if self.route:
            _dict['route'] = self.route.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ShipNav:
        """Create an instance of ShipNav from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ShipNav.parse_obj(obj)

        _obj = ShipNav.parse_obj({
            "system_symbol": obj.get("systemSymbol"),
            "waypoint_symbol": obj.get("waypointSymbol"),
            "route": ShipNavRoute.from_dict(obj.get("route")) if obj.get("route") is not None else None,
            "status": obj.get("status"),
            "flight_mode": obj.get("flightMode")
        })
        return _obj


