version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis_st
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "./redis:/data"
  postgres:
    container_name: postgres_st
    image: postgres:17.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - db_password
  influxdb:
    image: influxdb:latest
    container_name: influxdb_st
    restart: unless-stopped
    profiles: ["dbs", "all"]
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb2/config:/etc/influxdb2
      - ./influxdb2/db:/var/lib/influxdb2
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_st
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
      # - ./grafana/config:/etc/grafana
secrets:
  db_password:
    file: db_pw.txt
