# coding: utf-8

# flake8: noqa

"""
    SpaceTraders API

    SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   

    The version of the OpenAPI document: 2.0.0
    Contact: joel@spacetraders.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from .api import AgentsApi, ContractsApi, FactionsApi, FleetApi, SystemsApi, DefaultApi


# import ApiClient
from .api_response import ApiResponse
from .api_client import ApiClient
from .configuration import Configuration
from .exceptions import (
    OpenApiException,
    ApiTypeError,
    ApiValueError,
    ApiKeyError,
    ApiAttributeError,
    ApiException,
)

# import models into sdk package
from .models.accept_contract200_response import AcceptContract200Response
from .models.accept_contract200_response_data import AcceptContract200ResponseData
from .models.activity_level import ActivityLevel
from .models.agent import Agent
from .models.chart import Chart
from .models.construction import Construction
from .models.construction_material import ConstructionMaterial
from .models.contract import Contract
from .models.contract_deliver_good import ContractDeliverGood
from .models.contract_payment import ContractPayment
from .models.contract_terms import ContractTerms
from .models.cooldown import Cooldown
from .models.create_chart201_response import CreateChart201Response
from .models.create_chart201_response_data import CreateChart201ResponseData
from .models.create_ship_ship_scan201_response import CreateShipShipScan201Response
from .models.create_ship_ship_scan201_response_data import (
    CreateShipShipScan201ResponseData,
)
from .models.create_ship_system_scan201_response import CreateShipSystemScan201Response
from .models.create_ship_system_scan201_response_data import (
    CreateShipSystemScan201ResponseData,
)
from .models.create_ship_waypoint_scan201_response import (
    CreateShipWaypointScan201Response,
)
from .models.create_ship_waypoint_scan201_response_data import (
    CreateShipWaypointScan201ResponseData,
)
from .models.create_survey201_response import CreateSurvey201Response
from .models.create_survey201_response_data import CreateSurvey201ResponseData
from .models.deliver_contract200_response import DeliverContract200Response
from .models.deliver_contract200_response_data import DeliverContract200ResponseData
from .models.deliver_contract_request import DeliverContractRequest
from .models.dock_ship200_response import DockShip200Response
from .models.extract_resources201_response import ExtractResources201Response
from .models.extract_resources201_response_data import ExtractResources201ResponseData
from .models.extract_resources201_response_data_events_inner import (
    ExtractResources201ResponseDataEventsInner,
)
from .models.extract_resources_request import ExtractResourcesRequest
from .models.extraction import Extraction
from .models.extraction_yield import ExtractionYield
from .models.faction import Faction
from .models.faction_symbol import FactionSymbol
from .models.faction_trait import FactionTrait
from .models.faction_trait_symbol import FactionTraitSymbol
from .models.fulfill_contract200_response import FulfillContract200Response
from .models.get_agents200_response import GetAgents200Response
from .models.get_construction200_response import GetConstruction200Response
from .models.get_contract200_response import GetContract200Response
from .models.get_contracts200_response import GetContracts200Response
from .models.get_faction200_response import GetFaction200Response
from .models.get_factions200_response import GetFactions200Response
from .models.get_jump_gate200_response import GetJumpGate200Response
from .models.get_market200_response import GetMarket200Response
from .models.get_mounts200_response import GetMounts200Response
from .models.get_my_agent200_response import GetMyAgent200Response
from .models.get_my_ship200_response import GetMyShip200Response
from .models.get_my_ship_cargo200_response import GetMyShipCargo200Response
from .models.get_my_ships200_response import GetMyShips200Response
from .models.get_repair_ship200_response import GetRepairShip200Response
from .models.get_repair_ship200_response_data import GetRepairShip200ResponseData
from .models.get_scrap_ship200_response import GetScrapShip200Response
from .models.get_scrap_ship200_response_data import GetScrapShip200ResponseData
from .models.get_ship_cooldown200_response import GetShipCooldown200Response
from .models.get_ship_nav200_response import GetShipNav200Response
from .models.get_shipyard200_response import GetShipyard200Response
from .models.get_status200_response import GetStatus200Response
from .models.get_status200_response_announcements_inner import (
    GetStatus200ResponseAnnouncementsInner,
)
from .models.get_status200_response_leaderboards import GetStatus200ResponseLeaderboards
from .models.get_status200_response_leaderboards_most_credits_inner import (
    GetStatus200ResponseLeaderboardsMostCreditsInner,
)
from .models.get_status200_response_leaderboards_most_submitted_charts_inner import (
    GetStatus200ResponseLeaderboardsMostSubmittedChartsInner,
)
from .models.get_status200_response_links_inner import GetStatus200ResponseLinksInner
from .models.get_status200_response_server_resets import (
    GetStatus200ResponseServerResets,
)
from .models.get_status200_response_stats import GetStatus200ResponseStats
from .models.get_system200_response import GetSystem200Response
from .models.get_system_waypoints200_response import GetSystemWaypoints200Response
from .models.get_system_waypoints_traits_parameter import (
    GetSystemWaypointsTraitsParameter,
)
from .models.get_systems200_response import GetSystems200Response
from .models.get_waypoint200_response import GetWaypoint200Response
from .models.install_mount201_response import InstallMount201Response
from .models.install_mount201_response_data import InstallMount201ResponseData
from .models.install_mount_request import InstallMountRequest
from .models.jettison200_response import Jettison200Response
from .models.jettison200_response_data import Jettison200ResponseData
from .models.jettison_request import JettisonRequest
from .models.jump_gate import JumpGate
from .models.jump_ship200_response import JumpShip200Response
from .models.jump_ship200_response_data import JumpShip200ResponseData
from .models.jump_ship_request import JumpShipRequest
from .models.market import Market
from .models.market_trade_good import MarketTradeGood
from .models.market_transaction import MarketTransaction
from .models.meta import Meta
from .models.navigate_ship200_response import NavigateShip200Response
from .models.navigate_ship200_response_data import NavigateShip200ResponseData
from .models.navigate_ship_request import NavigateShipRequest
from .models.negotiate_contract200_response import NegotiateContract200Response
from .models.negotiate_contract200_response_data import NegotiateContract200ResponseData
from .models.orbit_ship200_response import OrbitShip200Response
from .models.orbit_ship200_response_data import OrbitShip200ResponseData
from .models.patch_ship_nav_request import PatchShipNavRequest
from .models.purchase_cargo201_response import PurchaseCargo201Response
from .models.purchase_cargo_request import PurchaseCargoRequest
from .models.purchase_ship201_response import PurchaseShip201Response
from .models.purchase_ship201_response_data import PurchaseShip201ResponseData
from .models.purchase_ship_request import PurchaseShipRequest
from .models.refuel_ship200_response import RefuelShip200Response
from .models.refuel_ship200_response_data import RefuelShip200ResponseData
from .models.refuel_ship_request import RefuelShipRequest
from .models.register201_response import Register201Response
from .models.register201_response_data import Register201ResponseData
from .models.register_request import RegisterRequest
from .models.remove_mount201_response import RemoveMount201Response
from .models.remove_mount201_response_data import RemoveMount201ResponseData
from .models.remove_mount_request import RemoveMountRequest
from .models.repair_ship200_response import RepairShip200Response
from .models.repair_ship200_response_data import RepairShip200ResponseData
from .models.repair_transaction import RepairTransaction
from .models.scanned_ship import ScannedShip
from .models.scanned_ship_engine import ScannedShipEngine
from .models.scanned_ship_frame import ScannedShipFrame
from .models.scanned_ship_mounts_inner import ScannedShipMountsInner
from .models.scanned_ship_reactor import ScannedShipReactor
from .models.scanned_system import ScannedSystem
from .models.scanned_waypoint import ScannedWaypoint
from .models.scrap_ship200_response import ScrapShip200Response
from .models.scrap_ship200_response_data import ScrapShip200ResponseData
from .models.scrap_transaction import ScrapTransaction
from .models.sell_cargo201_response import SellCargo201Response
from .models.sell_cargo201_response_data import SellCargo201ResponseData
from .models.sell_cargo_request import SellCargoRequest
from .models.ship import Ship
from .models.ship_cargo import ShipCargo
from .models.ship_cargo_item import ShipCargoItem
from .models.ship_condition_event import ShipConditionEvent
from .models.ship_crew import ShipCrew
from .models.ship_engine import ShipEngine
from .models.ship_frame import ShipFrame
from .models.ship_fuel import ShipFuel
from .models.ship_fuel_consumed import ShipFuelConsumed
from .models.ship_modification_transaction import ShipModificationTransaction
from .models.ship_module import ShipModule
from .models.ship_mount import ShipMount
from .models.ship_nav import ShipNav
from .models.ship_nav_flight_mode import ShipNavFlightMode
from .models.ship_nav_route import ShipNavRoute
from .models.ship_nav_route_waypoint import ShipNavRouteWaypoint
from .models.ship_nav_status import ShipNavStatus
from .models.ship_reactor import ShipReactor
from .models.ship_refine201_response import ShipRefine201Response
from .models.ship_refine201_response_data import ShipRefine201ResponseData
from .models.ship_refine201_response_data_produced_inner import (
    ShipRefine201ResponseDataProducedInner,
)
from .models.ship_refine_request import ShipRefineRequest
from .models.ship_registration import ShipRegistration
from .models.ship_requirements import ShipRequirements
from .models.ship_role import ShipRole
from .models.ship_type import ShipType
from .models.shipyard import Shipyard
from .models.shipyard_ship import ShipyardShip
from .models.shipyard_ship_crew import ShipyardShipCrew
from .models.shipyard_ship_types_inner import ShipyardShipTypesInner
from .models.shipyard_transaction import ShipyardTransaction
from .models.siphon import Siphon
from .models.siphon_resources201_response import SiphonResources201Response
from .models.siphon_resources201_response_data import SiphonResources201ResponseData
from .models.siphon_yield import SiphonYield
from .models.supply_construction201_response import SupplyConstruction201Response
from .models.supply_construction201_response_data import (
    SupplyConstruction201ResponseData,
)
from .models.supply_construction_request import SupplyConstructionRequest
from .models.supply_level import SupplyLevel
from .models.survey import Survey
from .models.survey_deposit import SurveyDeposit
from .models.system import System
from .models.system_faction import SystemFaction
from .models.system_type import SystemType
from .models.system_waypoint import SystemWaypoint
from .models.trade_good import TradeGood
from .models.trade_symbol import TradeSymbol
from .models.transfer_cargo200_response import TransferCargo200Response
from .models.transfer_cargo_request import TransferCargoRequest
from .models.warp_ship200_response import WarpShip200Response
from .models.warp_ship200_response_data import WarpShip200ResponseData
from .models.waypoint import Waypoint
from .models.waypoint_faction import WaypointFaction
from .models.waypoint_modifier import WaypointModifier
from .models.waypoint_modifier_symbol import WaypointModifierSymbol
from .models.waypoint_orbital import WaypointOrbital
from .models.waypoint_trait import WaypointTrait
from .models.waypoint_trait_symbol import WaypointTraitSymbol
from .models.waypoint_type import WaypointType
